### ISSUE TITLE
call to undefined xoops_getLinkedUnameFromId

### ISSUE THREAD

**Issue by fiammybe** [skenow/impresscms-module-wiwimod#7]
When running on ImpressCMS 1.4.2 on PHP 7.4, I get the following error message:
> Fatal error: Uncaught Error: Call to undefined function xoops_getLinkedUnameFromId() in /home/customer/www/impresscms.org/public_html/modules/simplywiki/index.php:440 Stack trace: #0 {main} thrown in /home/customer/www/impresscms.org/public_html/modules/simplywiki/index.php on line 440

**Comment by skenow** [comment]
This has been addressed in the upcoming 2.0 release
